"""AWE TraceGate's keyless, evidence-gated workflow review core."""

__version__ = "0.3.0"

from .adapters import import_generic_evaluation, import_otel_genai_evaluation
from .compiler import compile_traces
from .contracts import (
    AdapterConformanceReceipt,
    CapabilitiesDocument,
    ComparisonPolicy,
    ComparisonReceipt,
    ComparisonVerification,
    CompilationCandidate,
    CompilationReceipt,
    CompileRequest,
    EvaluationReceipt,
    EvidenceEnvelope,
    EvidencePackage,
    ExecutionTrace,
    ExperimentManifest,
    ExperimentQualityEvidence,
    ExperimentQualityReceipt,
    ExplanationReceipt,
    GateReceipt,
    GateReceiptV2,
    PromotionReceipt,
    QualityPolicy,
    ReceiptVerification,
    ReviewBundleReport,
    SensitivityPolicy,
    SensitivityReceipt,
    SignatureVerification,
    SkillBom,
)
from .demo import generate_demo, inspect_review_bundle
from .discovery import (
    AgentTraceReceipt,
    FailureClusterReport,
    MigrationDiscoveryBundle,
    PostgresAlembicExperiment,
    TraceCaptureConsent,
    build_migration_discovery_bundle,
    import_agent_trace,
)
from .evaluation import (
    compare_experiments,
    evaluate_candidate,
    validate_comparison_receipt_inputs,
    verify_comparison_receipt_inputs,
)
from .evidence import (
    create_evidence_envelope,
    create_evidence_package,
    validate_evidence_envelope,
)
from .explain import explain_receipt
from .gate import (
    GateReplayExpectations,
    gate_evidence,
    gate_evidence_v2,
    validate_gate_receipt_inputs,
    validate_gate_v2_receipt_inputs,
)
from .intervention import (
    DiscoveryIntervention,
    DiscoveryReplayRequest,
    InterventionApproval,
    approve_intervention,
    prepare_replay_request,
    propose_intervention,
)
from .quality import assess_experiment_quality
from .recipes import (
    DecisionRecipe,
    DecisionRecipeCatalog,
    RecipeScaffoldManifest,
    build_recipe_scaffold,
    decision_recipe_catalog,
    initialize_evidence_workspace,
)
from .sensitivity import assess_sensitivity
from .skill_bom import inspect_skill
from .verifier import verify_compilation_receipt
from .workspace_status import WorkspaceStatusReport, inspect_workspace_status

__all__ = [
    "AdapterConformanceReceipt",
    "AgentTraceReceipt",
    "CapabilitiesDocument",
    "ComparisonPolicy",
    "ComparisonReceipt",
    "ComparisonVerification",
    "CompilationCandidate",
    "CompilationReceipt",
    "CompileRequest",
    "DecisionRecipe",
    "DecisionRecipeCatalog",
    "DiscoveryIntervention",
    "DiscoveryReplayRequest",
    "EvaluationReceipt",
    "EvidenceEnvelope",
    "EvidencePackage",
    "ExecutionTrace",
    "ExperimentManifest",
    "ExperimentQualityEvidence",
    "ExperimentQualityReceipt",
    "ExplanationReceipt",
    "FailureClusterReport",
    "GateReceipt",
    "GateReceiptV2",
    "GateReplayExpectations",
    "InterventionApproval",
    "MigrationDiscoveryBundle",
    "PostgresAlembicExperiment",
    "PromotionReceipt",
    "QualityPolicy",
    "ReceiptVerification",
    "RecipeScaffoldManifest",
    "ReviewBundleReport",
    "SensitivityPolicy",
    "SensitivityReceipt",
    "SignatureVerification",
    "SkillBom",
    "TraceCaptureConsent",
    "WorkspaceStatusReport",
    "approve_intervention",
    "assess_experiment_quality",
    "assess_sensitivity",
    "build_migration_discovery_bundle",
    "build_recipe_scaffold",
    "compare_experiments",
    "compile_traces",
    "create_evidence_envelope",
    "create_evidence_package",
    "decision_recipe_catalog",
    "evaluate_candidate",
    "explain_receipt",
    "gate_evidence",
    "gate_evidence_v2",
    "generate_demo",
    "import_agent_trace",
    "import_generic_evaluation",
    "import_otel_genai_evaluation",
    "initialize_evidence_workspace",
    "inspect_review_bundle",
    "inspect_skill",
    "inspect_workspace_status",
    "prepare_replay_request",
    "propose_intervention",
    "validate_comparison_receipt_inputs",
    "validate_evidence_envelope",
    "validate_gate_receipt_inputs",
    "validate_gate_v2_receipt_inputs",
    "verify_comparison_receipt_inputs",
    "verify_compilation_receipt",
]
