/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compile Workflow */
        post: operations["compile_workflow_v1_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate */
        post: operations["evaluate_v1_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/experiments/import/generic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Experiment */
        post: operations["import_experiment_v1_experiments_import_generic_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/experiments/import/otlp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Otlp Experiment
         * @description Normalize a pinned OTLP GenAI export without executing its spans.
         */
        post: operations["import_otlp_experiment_v1_experiments_import_otlp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote */
        post: operations["promote_v1_promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Receipt */
        post: operations["verify_receipt_v1_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CompilationCandidate
         * @description Declarative candidate; it is safe to evaluate, not auto-promote.
         */
        CompilationCandidate: {
            /** Candidate Digest */
            candidate_digest: string;
            /**
             * Dependencies
             * @default []
             */
            dependencies: components["schemas"]["DependencyEvidence"][];
            /**
             * Effect Scope
             * @default pure_or_read
             * @constant
             */
            effect_scope: "pure_or_read";
            /** Intent */
            intent: string;
            /** Nodes */
            nodes: components["schemas"]["CompiledNode"][];
            /**
             * Schema Version
             * @default awe.candidate.v1
             * @constant
             */
            schema_version: "awe.candidate.v1";
            /** Source Trace Ids */
            source_trace_ids: string[];
        };
        /**
         * CompilationReceipt
         * @description Deterministic receipt for either compilation or a safe refusal.
         */
        CompilationReceipt: {
            candidate?: components["schemas"]["CompilationCandidate"] | null;
            /**
             * Compiler Version
             * @default awe.compiler.v1
             * @constant
             */
            compiler_version: "awe.compiler.v1";
            /** Input Bundle Digest */
            input_bundle_digest: string;
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            /** Receipt Hash */
            receipt_hash: string;
            /**
             * Schema Version
             * @default awe.compilation-receipt.v1
             * @constant
             */
            schema_version: "awe.compilation-receipt.v1";
            /**
             * Status
             * @enum {string}
             */
            status: "compiled" | "refused";
        };
        /**
         * CompileRequest
         * @description Trace set proposed for compilation.
         */
        CompileRequest: {
            /** Traces */
            traces: components["schemas"]["ExecutionTrace"][];
        };
        /**
         * CompiledBinding
         * @description Binding retained in a declarative compiled candidate.
         */
        CompiledBinding: {
            /** Input Name */
            input_name: string;
            /** Source Field */
            source_field: string;
            /**
             * Source Kind
             * @enum {string}
             */
            source_kind: "workflow_input" | "step_output";
            /** Source Node */
            source_node?: string | null;
        };
        /**
         * CompiledNode
         * @description Read-only node emitted into a candidate workflow.
         */
        CompiledNode: {
            /**
             * Effect
             * @enum {string}
             */
            effect: "pure" | "read";
            /**
             * Inputs
             * @default []
             */
            inputs: components["schemas"]["CompiledBinding"][];
            /** Node Id */
            node_id: string;
            /** Output Fields */
            output_fields: string[];
            /** Tool */
            tool: string;
            /** Tool Version */
            tool_version: string;
        };
        /**
         * DependencyEvidence
         * @description Auditable producer-to-consumer dependency observed in every trace.
         */
        DependencyEvidence: {
            /** Consumer Input */
            consumer_input: string;
            /** Consumer Node */
            consumer_node: string;
            /** Evidence Digest */
            evidence_digest: string;
            /** Observation Count */
            observation_count: number;
            /** Producer Field */
            producer_field: string;
            /** Producer Node */
            producer_node: string;
            /** Trace Ids */
            trace_ids: string[];
        };
        /** EvaluateRequest */
        EvaluateRequest: {
            baseline: components["schemas"]["EvaluationBundle"];
            candidate: components["schemas"]["EvaluationBundle"];
            /**
             * @default {
             *       "maximum_cost_increase_bps": 2500,
             *       "maximum_latency_increase_bps": 2500,
             *       "maximum_success_regression_bps": 200,
             *       "minimum_trials": 3,
             *       "require_zero_safety_violations": true,
             *       "schema_version": "awe.evaluation-policy.v1"
             *     }
             */
            policy: components["schemas"]["EvaluationPolicy"];
        };
        /**
         * EvaluationBundle
         * @description Frozen evaluation results for one exact subject and dataset.
         */
        EvaluationBundle: {
            /** Dataset Digest */
            dataset_digest: string;
            /**
             * Schema Version
             * @default awe.evaluation-bundle.v1
             * @constant
             */
            schema_version: "awe.evaluation-bundle.v1";
            /** Subject Digest */
            subject_digest: string;
            /** Trials */
            trials: components["schemas"]["EvaluationTrial"][];
        };
        /** EvaluationMetrics */
        EvaluationMetrics: {
            /** P95 Latency Ms */
            p95_latency_ms: number;
            /** Safety Violations */
            safety_violations: number;
            /** Success Count */
            success_count: number;
            /** Success Rate Bps */
            success_rate_bps: number;
            /** Total Cost Microusd */
            total_cost_microusd: number;
            /** Trial Count */
            trial_count: number;
        };
        /**
         * EvaluationPolicy
         * @description Deterministic non-regression and safety policy.
         */
        EvaluationPolicy: {
            /**
             * Maximum Cost Increase Bps
             * @default 2500
             */
            maximum_cost_increase_bps: number;
            /**
             * Maximum Latency Increase Bps
             * @default 2500
             */
            maximum_latency_increase_bps: number;
            /**
             * Maximum Success Regression Bps
             * @default 200
             */
            maximum_success_regression_bps: number;
            /**
             * Minimum Trials
             * @default 3
             */
            minimum_trials: number;
            /**
             * Require Zero Safety Violations
             * @default true
             */
            require_zero_safety_violations: boolean;
            /**
             * Schema Version
             * @default awe.evaluation-policy.v1
             * @constant
             */
            schema_version: "awe.evaluation-policy.v1";
        };
        /**
         * EvaluationReceipt
         * @description Fail-closed comparison of a baseline and candidate on one frozen dataset.
         */
        EvaluationReceipt: {
            baseline: components["schemas"]["EvaluationMetrics"];
            /** Baseline Digest */
            baseline_digest: string;
            candidate: components["schemas"]["EvaluationMetrics"];
            /** Candidate Digest */
            candidate_digest: string;
            /** Dataset Digest */
            dataset_digest: string;
            /**
             * Evaluator Version
             * @default awe.evaluator.v1
             * @constant
             */
            evaluator_version: "awe.evaluator.v1";
            /** Policy Digest */
            policy_digest: string;
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            /** Receipt Hash */
            receipt_hash: string;
            /**
             * Schema Version
             * @default awe.evaluation-receipt.v1
             * @constant
             */
            schema_version: "awe.evaluation-receipt.v1";
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "review" | "block";
        };
        /**
         * EvaluationTrial
         * @description One deterministic outcome record from an external evaluation harness.
         */
        EvaluationTrial: {
            /** Case Id */
            case_id: string;
            /**
             * Cost Microusd
             * @default 0
             */
            cost_microusd: number;
            /** Latency Ms */
            latency_ms: number;
            /**
             * Safety Violations
             * @default 0
             */
            safety_violations: number;
            /** Succeeded */
            succeeded: boolean;
            /** Trial Id */
            trial_id: string;
        };
        /**
         * ExecutionTrace
         * @description Immutable evidence from a single workflow execution.
         */
        ExecutionTrace: {
            /** Intent */
            intent: string;
            /**
             * Schema Version
             * @default awe.trace.v1
             * @constant
             */
            schema_version: "awe.trace.v1";
            /** Steps */
            steps: components["schemas"]["TraceStep"][];
            /** Succeeded */
            succeeded: boolean;
            /** Trace Id */
            trace_id: string;
            /** Workflow Inputs */
            workflow_inputs: components["schemas"]["FieldEvidence"][];
        };
        /**
         * ExperimentManifest
         * @description Content-addressed experiment evidence imported from one pinned format.
         */
        ExperimentManifest: {
            /** Commit Sha */
            commit_sha: string;
            /** Dataset Digest */
            dataset_digest: string;
            /** Dataset Split Digest */
            dataset_split_digest: string;
            /** Environment Digest */
            environment_digest: string;
            /** Experiment Id */
            experiment_id: string;
            /** Grader Digest */
            grader_digest: string;
            /** Harness Digest */
            harness_digest: string;
            /** Harness Name */
            harness_name: string;
            /** Harness Version */
            harness_version: string;
            /** Manifest Digest */
            manifest_digest: string;
            /** Model Config Digest */
            model_config_digest: string;
            /** Model Name */
            model_name: string;
            /** Model Provider */
            model_provider: string;
            /** Repository Uri */
            repository_uri: string;
            /**
             * Schema Version
             * @default awe.experiment-manifest.v1
             * @constant
             */
            schema_version: "awe.experiment-manifest.v1";
            /** Source Format */
            source_format: string;
            /** Source Revision */
            source_revision: string;
            /** Strategy Digest */
            strategy_digest: string;
            /** Strategy Name */
            strategy_name: string;
            /** Subject Digest */
            subject_digest: string;
            /** Trials */
            trials: components["schemas"]["ExperimentTrial"][];
        };
        /**
         * ExperimentRun
         * @description Provider-neutral evidence shared by generic and telemetry importers.
         */
        ExperimentRun: {
            /** Commit Sha */
            commit_sha: string;
            /** Dataset Digest */
            dataset_digest: string;
            /** Dataset Split Digest */
            dataset_split_digest: string;
            /** Environment Digest */
            environment_digest: string;
            /** Experiment Id */
            experiment_id: string;
            /** Grader Digest */
            grader_digest: string;
            /** Harness Digest */
            harness_digest: string;
            /** Harness Name */
            harness_name: string;
            /** Harness Version */
            harness_version: string;
            /** Model Config Digest */
            model_config_digest: string;
            /** Model Name */
            model_name: string;
            /** Model Provider */
            model_provider: string;
            /** Repository Uri */
            repository_uri: string;
            /** Strategy Digest */
            strategy_digest: string;
            /** Strategy Name */
            strategy_name: string;
            /** Subject Digest */
            subject_digest: string;
            /** Trials */
            trials: components["schemas"]["ExperimentTrial"][];
        };
        /**
         * ExperimentTrial
         * @description One frozen trial with quality, safety, token, cost, and trace evidence.
         */
        ExperimentTrial: {
            /**
             * Cached Input Tokens
             * @default 0
             */
            cached_input_tokens: number;
            /** Case Id */
            case_id: string;
            /** Cost Microusd */
            cost_microusd: number;
            /** Grader Result Digest */
            grader_result_digest: string;
            /** Input Tokens */
            input_tokens: number;
            /** Latency Ms */
            latency_ms: number;
            /** Output Tokens */
            output_tokens: number;
            /**
             * Safety Violations
             * @default 0
             */
            safety_violations: number;
            /** Seed */
            seed?: number | null;
            /** Succeeded */
            succeeded: boolean;
            /** Trace Id */
            trace_id?: string | null;
            /** Trial Id */
            trial_id: string;
        };
        /**
         * FieldEvidence
         * @description Content digest observed at a JSON field boundary.
         */
        FieldEvidence: {
            /** Field */
            field: string;
            /** Value Digest */
            value_digest: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Mode
             * @default offline_keyless
             * @constant
             */
            mode: "offline_keyless";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * PromotionReceipt
         * @description Human decision bound to a verified compilation and evaluation chain.
         */
        PromotionReceipt: {
            /** Actor Id */
            actor_id: string;
            /** Candidate Digest */
            candidate_digest: string;
            /** Commit Sha */
            commit_sha: string;
            /** Compilation Receipt Hash */
            compilation_receipt_hash: string;
            /** Dataset Digest */
            dataset_digest: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Evaluation Receipt Hash */
            evaluation_receipt_hash: string;
            /**
             * Evaluation Status
             * @enum {string}
             */
            evaluation_status: "pass" | "review" | "block";
            /** Input Bundle Digest */
            input_bundle_digest: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Policy Digest */
            policy_digest: string;
            /** Rationale */
            rationale: string;
            /** Receipt Hash */
            receipt_hash: string;
            /**
             * Schema Version
             * @default awe.promotion-receipt.v2
             * @constant
             */
            schema_version: "awe.promotion-receipt.v2";
            /** Traces Verified */
            traces_verified: boolean;
            /** Verification Receipt Hash */
            verification_receipt_hash: string;
            /**
             * Verification Status
             * @enum {string}
             */
            verification_status: "valid" | "invalid";
        };
        /**
         * PromotionRequest
         * @description Evidence inputs required to record a human promotion decision.
         */
        PromotionRequest: {
            /** Actor Id */
            actor_id: string;
            /** Commit Sha */
            commit_sha: string;
            compilation: components["schemas"]["CompilationReceipt"];
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            evaluation: components["schemas"]["EvaluationReceipt"];
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Rationale */
            rationale: string;
            /** Traces */
            traces: components["schemas"]["ExecutionTrace"][];
            verification: components["schemas"]["ReceiptVerification"];
        };
        /**
         * ReceiptVerification
         * @description Result of recomputing a compilation receipt and optional source traces.
         */
        ReceiptVerification: {
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            /** Receipt Hash */
            receipt_hash: string;
            /**
             * Schema Version
             * @default awe.receipt-verification.v2
             * @constant
             */
            schema_version: "awe.receipt-verification.v2";
            /**
             * Status
             * @enum {string}
             */
            status: "valid" | "invalid";
            /** Traces Verified */
            traces_verified: boolean;
            /** Verification Hash */
            verification_hash: string;
        };
        /**
         * TraceBinding
         * @description Observed input binding for one executed step.
         */
        TraceBinding: {
            /** Input Name */
            input_name: string;
            /** Observed Value Digest */
            observed_value_digest: string;
            /** Source Field */
            source_field: string;
            /**
             * Source Kind
             * @enum {string}
             */
            source_kind: "workflow_input" | "step_output" | "model_decision";
            /** Source Node */
            source_node?: string | null;
        };
        /**
         * TraceStep
         * @description One typed activity observed in an execution trace.
         */
        TraceStep: {
            /**
             * Effect
             * @enum {string}
             */
            effect: "pure" | "read" | "write" | "high_impact";
            /**
             * Inputs
             * @default []
             */
            inputs: components["schemas"]["TraceBinding"][];
            /** Node Id */
            node_id: string;
            /** Outputs */
            outputs: components["schemas"]["FieldEvidence"][];
            /** Tool */
            tool: string;
            /** Tool Version */
            tool_version: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerifyRequest */
        VerifyRequest: {
            receipt: components["schemas"]["CompilationReceipt"];
            /** Traces */
            traces?: components["schemas"]["ExecutionTrace"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    compile_workflow_v1_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompilationReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_v1_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_experiment_v1_experiments_import_generic_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentRun"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_otlp_experiment_v1_experiments_import_otlp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_v1_promote_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromotionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_receipt_v1_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptVerification"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
